name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: e2e
          install-command: npm install
          build: npm run build
          start: npm start
      - name: Generate report
        run: cd e2e && npm run cy:report
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-cucumber-report
          path: cypress/cucumber-report/